package edu.baylor.cs.se.hibernate;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestSocketTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testSocket() {
    driver.get("http://localhost:8080/index.html");
    driver.manage().window().setSize(new Dimension(1266, 664));
    driver.findElement(By.id("connect")).click();
    driver.findElement(By.id("send")).click();
    driver.findElement(By.id("edit-button")).click();
    driver.findElement(By.cssSelector("#userinfo > tr")).click();
    {
      WebElement element = driver.findElement(By.id("status"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'Pending'}", element);
    }
    driver.findElement(By.id("submit-btn")).click();
    {
      WebElement element = driver.findElement(By.id("submit-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
